name: duha_app
description: Start Your Morning With Clarity

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4 
  provider: ^6.0.5

  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

  # Storage & Backend
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3

  # File handling
  file_picker: ^6.1.1
  image_picker: ^1.0.7

  # Share functionality
  share_plus: ^7.2.1
  url_launcher: ^6.2.2

  # Charts & Analytics
  fl_chart: ^0.66.0
  intl: ^0.18.1

  # Models & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Routing
  go_router: ^14.2.0

  flutter_svg: ^2.0.9
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9   
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/img/logo.svg
  generate: true
